version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'microsoft-dotnet-core-sdk'
    steps:
      - checkout
      - run: dotnet build
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
