version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk'
    steps:
      - checkout
      - run: apt update
      - run: apt install -y unzip
      - run: dotnet build
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - scan:
          context: SonarCloud
