version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt update
            apt install --no-install-recommends -y default-jre
            dotnet tool install --global dotnet-sonarscanner
      - run:
          name: Build and Scan
          command: |
            export PATH="$PATH:/root/.dotnet/tools" 
            dotnet sonarscanner begin /k:wburklund_Habitica.NET /o:wburklund /d:sonar.host.url=https://sonarcloud.io /d:sonar-login=$SONAR_TOKEN
            dotnet build
            dotnet sonarscanner end
            
