version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: dotnet build
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
