version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk'
    steps:
      - checkout
#     - run: apt update
#     - run: apt install -y unzip
      - run:
          command: |
            dotnet tool install --global dotnet-sonarscanner
            export PATH="$PATH:/root/.dotnet/tools" 
            dotnet sonarscanner begin /k:"wburklund_Habitica.NET"
            dotnet build
            dotnet sonarscanner end
#     - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
