version: 2.1

jobs:
  build:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt update
            apt install -y default-jre
            dotnet tool install --global dotnet-sonarscanner
            export PATH="$PATH:/root/.dotnet/tools" 
      - run:
          name: Build and Scan
          command: |
            dotnet sonarscanner begin /k:"wburklund_Habitica.NET" /o:wburklund /d:sonar.host.url=https://sonarcloud.io /d:sonar-login=$SONAR_TOKEN
            dotnet build
            dotnet sonarscanner end
