version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apk update
            apk add openjdk14-jre-headless
            dotnet tool restore
      - run:
          name: Build, Test, and Scan
          command: |
            dotnet sonarscanner begin /k:wburklund_Habitica.NET /o:wburklund /d:sonar.host.url=https://sonarcloud.io /d:sonar-login=$SONAR_TOKEN /d:sonar.cs.opencover.reportsPaths=Habitica.NET.Tests/coverage.opencover.xml
            dotnet build
            dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            dotnet sonarscanner end
            
